# This is a basic workflow to help you get started with Actions

name: Build version 0.0.12-SNAPSHOT

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
# events but only for the master branch
on:
  push:
    branches: [ master, development ]
  pull_request:
    branches: [ master, development ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Deploy to repo
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
      run: mvn --settings settings.xml deploy
